In [53]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv("D:\ETL\python_training\scikit-learn\WA_Fn-UseC_-Sales-Win-Loss.csv")
le = preprocessing.LabelEncoder()
df.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,Exterior Accessories,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,Exterior Accessories,Car Accessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,Motorcycle Parts,Performance & Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,Shelters & RV,Performance & Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,Exterior Accessories,Car Accessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [54]:
df.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,Exterior Accessories,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,Exterior Accessories,Car Accessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,Motorcycle Parts,Performance & Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,Shelters & RV,Performance & Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,Exterior Accessories,Car Accessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [55]:
df['Supplies Subgroup']=le.fit_transform(df['Supplies Subgroup'])
df['Region'] = le.fit_transform(df['Region'])
df['Route To Market'] = le.fit_transform(df['Route To Market'])
df['Opportunity Result'] = le.fit_transform(df['Opportunity Result'])
df['Competitor Type'] = le.fit_transform(df['Competitor Type'])
df['Supplies Group'] = le.fit_transform(df['Supplies Group'])

In [56]:
feature_cols = [col for col in df.columns if col not in ['Opportunity Number','opportunity Result']]
target = df['Opportunity Result']
data = df[feature_cols]
data.head()

,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,2,0,3,0,76,1,13,104,101,0,5,5,0,2,0.69636,0.113985,0.154215,1
1,2,0,4,2,63,0,2,163,163,0,3,5,0,2,0.00000,1.000000,0.000000,1
2,5,2,4,2,24,1,7,82,82,7750,1,1,0,2,1.00000,0.000000,0.000000,1
3,8,2,1,2,16,0,5,124,124,0,1,1,0,0,1.00000,0.000000,0.000000,1
4,2,0,4,2,69,0,11,91,13,69756,1,1,0,2,0.00000,0.141125,0.000000,4

In [43]:
from sklearn.model_selection import GaussianNB
from sklearn.metrics import accuracy_score
gnb = GaussianNB()
pred = gnb.fit(x_train,y_train).predict(x_test)
print(pred)
accuracy_score(y-test,pred,normalize = True)

ImportError: cannot import name 'GaussianNB' from 'sklearn.model_selection' (d:\etl\env\lib\site-packages\sklearn\model_selection\__init__.py)

In [57]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.30,random_state = 10)
print(x_train)
print(y_test)

       Supplies Subgroup  Supplies Group  Region  Route To Market  \
58546                  6               2       0                0
38963                  5               2       4                2
56239                  4               0       6                0
18336                  5               2       4                0
73136                  3               0       6                0
...                  ...             ...     ...              ...
17904                  4               0       4                3
37597                  6               2       3                0
10201                  5               2       4                0
9372                   0               0       1                1
50496                  5               2       6                2

       Elapsed Days In Sales Stage  Opportunity Result  \
58546                           49                   0
38963                           25                   1
56239                           67                   0
18336                           63                   0
73136                           23                   0
...                            ...                 ...
17904                           63                   0
37597                           19                   1
10201                           83                   0
9372                            42                   1
50496                           42                   1

       Sales Stage Change Count  Total Days Identified Through Closing  \
58546                         2                                     24
38963                         3                                      3
56239                         4                                     14
18336                         2                                     11
73136                         2                                      0
...                         ...                                    ...
17904                         2                                     12
37597                         5                                     12
10201                         2                                      8
9372                          3                                      3
50496                         4                                      7

       Total Days Identified Through Qualified  Opportunity Amount USD  \
58546                                       24                   10000
38963                                        3                    2142
56239                                       14                    5000
18336                                       11                   20000
73136                                        0                  500000
...                                        ...                     ...
17904                                       12                   50000
37597                                       11                  133000
10201                                        8                    5000
9372                                         3                      18
50496                                        7                  384000

       Client Size By Revenue  Client Size By Employee Count  \
58546                       2                              1
38963                       1                              1
56239                       4                              5
18336                       3                              5
73136                       1                              1
...                       ...                            ...
17904                       1                              3
37597                       1                              1
10201                       4                              2
9372                        4                              3
50496                       1                              1

       Revenue From Client Past Two Years  Competitor Type  \
58546                                   0                2
38963                                   0                1
56239                                   0                2
18336                                   0                2
73136                                   0                2
...                                   ...              ...
17904                                   0                2
37597                                   0                2
10201                                   0                0
9372                                    0                1
50496                                   0                2

       Ratio Days Identified To Total Days  \
58546                             1.000000
38963                             0.000000
56239                             0.285714
18336                             0.000000
73136                             0.000000
...                                    ...
17904                             1.000000
37597                             0.026087
10201                             1.000000
9372                              0.000000
50496                             0.202899

       Ratio Days Validated To Total Days  Ratio Days Qualified To Total Days  \
58546                            0.000000                            0.000000
38963                            1.000000                            0.000000
56239                            0.142857                            0.571429
18336                            1.000000                            0.000000
73136                            0.000000                            0.000000
...                                   ...                                 ...
17904                            0.000000                            0.000000
37597                            0.008696                            0.939130
10201                            0.000000                            0.000000
9372                             1.000000                            0.000000
50496                            0.797101                            0.000000

       Deal Size Category
58546                   2
38963                   1
56239                   1
18336                   2
73136                   7
...                   ...
17904                   4
37597                   5
10201                   1
9372                    1
50496                   6

[54617 rows x 18 columns]
66103    0
50020    0
74422    0
25496    1
53272    1
        ..
65650    0
25662    0
36087    0
28442    0
21445    0
Name: Opportunity Result, Length: 23408, dtype: int32

In [58]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
gnb = GaussianNB()
pred = gnb.fit(x_train,y_train).predict(x_test)
print(pred)
accuracy_score(y_test,pred,normalize = True)

[0 0 0 ... 0 0 1]

0.7745215311004785

In [51]:
from sklearn.svm import LinearSVC
from sklearn.metrics import acccuracy_score
svc_model = LinearSVC(random_state=1,max_iter = 100)
pred = svc_model.fit(x_train,y_train).predict(x_test)
print(pred)
accuracy_score(y_test,pred,normalize = True)

ImportError: cannot import name 'acccuracy_score' from 'sklearn.metrics' (d:\etl\env\lib\site-packages\sklearn\metrics\__init__.py)

In [59]:
from sklearn.neighbors  import KNeighborsClassifier
from sklearn.metrics import acccuracy_score
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train,y_train)
pred = neigh.predict(x_test)
accuracy_score(y-test,pred,normalize = True)

ImportError: cannot import name 'acccuracy_score' from 'sklearn.metrics' (d:\etl\env\lib\site-packages\sklearn\metrics\__init__.py)

In [62]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import acccuracy_score
import matplotlib.pyplot as plt
import numpy as np

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.30, random_state = 10)
reg = LinearRegression()
reg.fit(x_train, y_train)
pred = reg.predict(x_test)
print("pred===",pred)
print("reg.coef_==",reg.intercept_)
print("reg.intercept_==",reg.intercept_)
print("len(x_test)==",len(x_test))
print("y_test==",len(y_test))

ImportError: cannot import name 'acccuracy_score' from 'sklearn.metrics' (d:\etl\env\lib\site-packages\sklearn\metrics\__init__.py)